import type { DropdownItem } from "@/app/_types/dropdownItem";

const baseApiUrl = process.env.NEXT_PUBLIC_SWAPI_BASE_URL;

export const getHomeworldDropdownItems = (): DropdownItem[] => [
    { value: `${baseApiUrl}/planets/1/`, label: "Tatooine" },
    { value: `${baseApiUrl}/planets/2/`, label: "Alderaan" },
    { value: `${baseApiUrl}/planets/3/`, label: "Yavin IV" },
    { value: `${baseApiUrl}/planets/4/`, label: "Hoth" },
    { value: `${baseApiUrl}/planets/5/`, label: "Dagobah" },
    { value: `${baseApiUrl}/planets/6/`, label: "Bespin" },
    { value: `${baseApiUrl}/planets/7/`, label: "Endor" },
    { value: `${baseApiUrl}/planets/8/`, label: "Naboo" },
    { value: `${baseApiUrl}/planets/9/`, label: "Coruscant" },
    { value: `${baseApiUrl}/planets/10/`, label: "Kamino" },
    { value: `${baseApiUrl}/planets/11/`, label: "Geonosis" },
    { value: `${baseApiUrl}/planets/12/`, label: "Utapau" },
    { value: `${baseApiUrl}/planets/13/`, label: "Mustafar" },
    { value: `${baseApiUrl}/planets/14/`, label: "Kashyyyk" },
    { value: `${baseApiUrl}/planets/15/`, label: "Polis Massa" },
    { value: `${baseApiUrl}/planets/16/`, label: "Mygeeto" },
    { value: `${baseApiUrl}/planets/17/`, label: "Felucia" },
    { value: `${baseApiUrl}/planets/18/`, label: "Cato Neimoidia" },
    { value: `${baseApiUrl}/planets/19/`, label: "Saleucami" },
    { value: `${baseApiUrl}/planets/20/`, label: "Stewjon" },
    { value: `${baseApiUrl}/planets/21/`, label: "Eriadu" },
    { value: `${baseApiUrl}/planets/22/`, label: "Corellia" },
    { value: `${baseApiUrl}/planets/23 /`, label: "Rodia" },
    { value: `${baseApiUrl}/planets/24/`, label: "Nal Hutta" },
    { value: `${baseApiUrl}/planets/25/`, label: "Dantooine" },
    { value: `${baseApiUrl}/planets/26/`, label: "Bestine IV" },
    { value: `${baseApiUrl}/planets/27/`, label: "Ord Mantell" },
    { value: `${baseApiUrl}/planets/28/`, label: "unknown" },
    { value: `${baseApiUrl}/planets/29/`, label: "Trandosha" },
    { value: `${baseApiUrl}/planets/30/`, label: "Socorro" },
    { value: `${baseApiUrl}/planets/31/`, label: "Mon Cala" },
    { value: `${baseApiUrl}/planets/32/`, label: "Chandrila" },
    { value: `${baseApiUrl}/planets/33/`, label: "Sullust" },
    { value: `${baseApiUrl}/planets/34/`, label: "Toydaria" },
    { value: `${baseApiUrl}/planets/35/`, label: "Malastare" },
    { value: `${baseApiUrl}/planets/36/`, label: "Dathomir" },
    { value: `${baseApiUrl}/planets/37/`, label: "Ryloth" },
    { value: `${baseApiUrl}/planets/38/`, label: "Aleen Minor" },
    { value: `${baseApiUrl}/planets/39/`, label: "Vulpter" },
    { value: `${baseApiUrl}/planets/40/`, label: "Troiken" },
    { value: `${baseApiUrl}/planets/41/`, label: "Tund" },
    { value: `${baseApiUrl}/planets/42/`, label: "Haruun Kal" },
    { value: `${baseApiUrl}/planets/43/`, label: "Cerea" },
    { value: `${baseApiUrl}/planets/44/`, label: "Glee Anselm" },
    { value: `${baseApiUrl}/planets/45/`, label: "Iridonia" },
    { value: `${baseApiUrl}/planets/46/`, label: "Tholoth" },
    { value: `${baseApiUrl}/planets/47/`, label: "Iktotch" },
    { value: `${baseApiUrl}/planets/48/`, label: "Quermia" },
    { value: `${baseApiUrl}/planets/49/`, label: "Dorin" },
    { value: `${baseApiUrl}/planets/50/`, label: "Champala" },
    { value: `${baseApiUrl}/planets/51/`, label: "Mirial" },
    { value: `${baseApiUrl}/planets/52/`, label: "Serenno" },
    { value: `${baseApiUrl}/planets/53/`, label: "Concord Dawn" },
    { value: `${baseApiUrl}/planets/54/`, label: "Zolan" },
    { value: `${baseApiUrl}/planets/55/`, label: "Ojom" },
    { value: `${baseApiUrl}/planets/56/`, label: "Skako" },
    { value: `${baseApiUrl}/planets/57/`, label: "Muunilinst" },
    { value: `${baseApiUrl}/planets/58/`, label: "Shili" },
    { value: `${baseApiUrl}/planets/59/`, label: "Kalee" },
    { value: `${baseApiUrl}/planets/60/`, label: "Umbara" },
];
