name: Deploy

on:
  push:
    branches:
      - "main"

env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
  NEXT_PUBLIC_SWAPI_BASE_URL: ${{ vars.NEXT_PUBLIC_SWAPI_BASE_URL}}
  NEXT_PUBLIC_STAR_WARS_ASSETS_BASE_URL: ${{ vars.NEXT_PUBLIC_STAR_WARS_ASSETS_BASE_URL}}

jobs:
  docker-build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_SWAPI_BASE_URL=${{ env.NEXT_PUBLIC_SWAPI_BASE_URL }}
            NEXT_PUBLIC_STAR_WARS_ASSETS_BASE_URL=${{ env.NEXT_PUBLIC_STAR_WARS_ASSETS_BASE_URL }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - name: Deploy Docker image on server
      uses: appleboy/ssh-action@v1.0.3
      env:
        GHCR_USERNAME: ${{ github.repository_owner }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      with:
        host: ${{ secrets.SERVER_HOSTNAME }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        envs: GHCR_USERNAME, GHCR_TOKEN
        script: |
          echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
          cd star-wars-character
          docker compose pull
          docker compose up -d
